### PR TITLE
'__init__.py' file created, for converting server file into a package

### PR DESCRIPTION
**Pull request by AloisWagner**
I added the '__init__.py' file in the 'server' folder to convert it into a python-package. Now the codes should be executable  according to the README.md descripton.

### CODE REVIEW

**Comment by samhab** [comment]
Hi @AloisWagner 
Thank you for your suggestion. We are, however, not sure what problem should be fixed with this change. All commands in the README execute successfully in our environments when followed step by step.
Could you please provide more details about the issue you encountered?

**Comment by AloisWagner** [comment]
Hi @samhab,
sorry, I didn't know that this 'pull request' went directly to you as owner. We created a fork of your directory and each member cloned the forked directory to his local directory. I thought thereby, that this changes would stay within our forked directory, and my group members would be informed about the 'pull request'.

My problem was, that by trying to run the benchmark codes, the python files in the server folder couldn't be found (at least on my computer). I thought this is due to the fact, that the server files are not stored as python package and thereby can not be imported in the bechmark files.

You can ignore or deny my 'pull request'. I didn't want to push it in that directory. 
But I am wondering: with **'git remote -v'** i see our forked remote directory. I don't understand why my pull-request went to you as owner. I can as well see my branch in our forked directory. It is confusing to me, sorry.

**Comment by samhab** [comment]
Hi @AloisWagner 
You don't have to apologize at all. We've found out what led to that "unexpected" behavior of pull requests. When you create a pull request from a forked repository, it will, by default, propose the changes to the original repository (see print screen below). We weren't aware of this behavior too. In order to create a pull request for your teammates, you need to set the "base repository" to your own repo.
fork-default-pr-repo

Regarding your problem with running the benchmark. Did you set the PYTHONPATH environment variable before executing the benchmark script? If yes, make sure that it contains the path to your repo-root directory.

**Comment by AloisWagner** [comment]
Hi @samhab 
yes indeed, I was located in the wrong path when I run the command-lines to execute the python file. I didn't pay attention to the note in the README.md. Now it works out. Thanks!

**Pull request closed without merging**
